struct HelloWorld
{
	unsigned long index;
	string message;
};

struct KeyedHelloWorld
{
    @Key
    unsigned short key;
	unsigned long index;
	string message;
};

struct FixedSize
{
	unsigned short index;
};

struct Data64kb
{
    sequence<octet, 63996> data;
};

struct Data1mb
{
    sequence<octet, 1024000> data;
};

struct KeyedData1mb
{
    @Key
    unsigned short key;
    sequence<octet, 1023996> data;
};

struct StringType
{
    string<10000> message;
};
