// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file calculator_details.hpp
 * This header file contains support data structures for RPC communication.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__CALCULATOR_DETAILS_HPP
#define FAST_DDS_GENERATED__CALCULATOR_DETAILS_HPP

#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/rpc/RemoteExceptionCode_t.hpp>
#include <fastdds/dds/rpc/interfaces/RpcStatusCode.hpp>

#include "calculator.hpp"

namespace calculator_base {
    namespace detail {

    //{ Adder interface

    //{ addition
    struct Adder_addition_In
    {
        int32_t value1; 
        int32_t value2; 
    };

      

    struct Adder_addition_Out
    {
        int32_t return_;
    };

    struct Adder_addition_Result
    {
        eprosima::fastcdr::optional<calculator_base::detail::Adder_addition_Out> result;
        eprosima::fastcdr::optional<calculator_base::OverflowException> calculator_base_OverflowException_ex;
    };

    //}  // addition
     

    //}  // Adder interface

    } // namespace detail
    namespace detail {

    //{ Subtractor interface

    //{ subtraction
    struct Subtractor_subtraction_In
    {
        int32_t value1; 
        int32_t value2; 
    };

      

    struct Subtractor_subtraction_Out
    {
        int32_t return_;
    };

    struct Subtractor_subtraction_Result
    {
        eprosima::fastcdr::optional<calculator_base::detail::Subtractor_subtraction_Out> result;
        eprosima::fastcdr::optional<calculator_base::OverflowException> calculator_base_OverflowException_ex;
    };

    //}  // subtraction
     

    //}  // Subtractor interface

    } // namespace detail
}  // namespace calculator_base
namespace detail {

//{ Calculator interface

//{ representation_limits
struct Calculator_representation_limits_In
{
};



struct Calculator_representation_limits_Result
{
    eprosima::fastcdr::optional<detail::Calculator_representation_limits_Out> result;
};

//}  // representation_limits
 

//{ top level

struct Calculator_Request
{
    eprosima::fastcdr::optional<calculator_base::detail::Adder_addition_In> addition;   
    eprosima::fastcdr::optional<calculator_base::detail::Subtractor_subtraction_In> subtraction;   
    eprosima::fastcdr::optional<detail::Calculator_representation_limits_In> representation_limits; 
};

struct Calculator_Reply
{
    eprosima::fastcdr::optional<calculator_base::detail::Adder_addition_Result> addition; 
    eprosima::fastcdr::optional<calculator_base::detail::Subtractor_subtraction_Result> subtraction; 
    eprosima::fastcdr::optional<detail::Calculator_representation_limits_Result> representation_limits; 
    eprosima::fastcdr::optional<eprosima::fastdds::dds::rpc::RemoteExceptionCode_t> remoteEx;
};

//}  // top level

//}  // Calculator interface

} // namespace detail

#endif //FAST_DDS_GENERATED__CALCULATOR_DETAILS_HPP